### ISSUE TITLE
FEATURE REQUEST: Add "Date Updated" to course page (all code labs)

### ISSUE THREAD

**Issue by oneezy** [PolymerLabs/prpl-ce-firebase#1]
It would be cool if you guys could add the `Date Updated` to the  main course page also, as opposed to just having it on the main code labs page. 

![image](https://cloud.githubusercontent.com/assets/7369575/26755750/133f07ac-485a-11e7-9f25-49adb517be43.png)

**Comment by keanulee** [comment]
@oneezy Features for the codelab viewer belong here - https://github.com/googlecodelabs/codelab-components. This repo is for the code specific to this codelab.

**Comment by oneezy** [comment]
Thanks.

Here's the new issue: https://github.com/googlecodelabs/codelab-components/issues/41
